apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: weather-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "{{ .Values.env.redisHost }}"
            - name: DB_HOST
              value: "{{ .Values.env.dbHost }}"
            - name: DB_PORT
              value: "{{ .Values.env.dbPort }}"
            - name: DB_USER
              value: "{{ .Values.env.dbUser }}"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.dbPassSecretName }}
                  key: {{ .Values.env.dbPassSecretKey }}
            - name: DB_NAME
              value: "{{ .Values.env.dbName }}"
            - name: DB_SSLMODE
              value: "{{ .Values.env.dbSslMode }}"
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.openweatherApiKeySecretName }}
                  key: {{ .Values.env.openweatherApiKeySecretKey }}