name: Destroy Infrastructure and App

on:
  workflow_dispatch: # Дозволяє запускати вручну з вкладки Actions

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 1. Спочатку зносимо Helm-ресурси з Kubernetes
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name weather-app-eks --region eu-central-1 || true

      - name: Uninstall Helm Chart
        run: |
          helm uninstall weather-app || true

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Руйнуємо інфраструктуру (з потрібним шлях до tf файлів)
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform