# ==========================================
# Backend Configuration (FastAPI)
# ==========================================
backend:
  replicaCount: 1
  image:
    repository: 389633344485.dkr.ecr.eu-central-1.amazonaws.com/weather-app-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000

# ==========================================
# Frontend Configuration (Nginx Reverse Proxy)
# ==========================================
frontend:
  replicaCount: 1
  image:
    repository: 389633344485.dkr.ecr.eu-central-1.amazonaws.com/weather-app-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80

# ==========================================
# Application Environment Variables
# ==========================================
env:
  redisHost: "weather-app-redis.k1hgle.0001.euc1.cache.amazonaws.com"
  dbHost: "weather-app-db.cpmymwigkxpx.eu-central-1.rds.amazonaws.com"
  dbPort: "5432"
  dbUser: "postgres"
  dbPass: "weatherpass123"
  dbName: "weather_db"
  dbSslMode: "require"
  openweatherApiKey: ""